language: go

go:
  - 1.11.x

go_import_path: github.com/renathoaz/go-serial

env:
  - TEST_OS=linux TEST_ARCH=386
  - TEST_OS=linux TEST_ARCH=amd64
  - TEST_OS=linux TEST_ARCH=arm
  - TEST_OS=windows TEST_ARCH=386
  - TEST_OS=windows TEST_ARCH=amd64
  - TEST_OS=darwin TEST_ARCH=386
  - TEST_OS=darwin TEST_ARCH=amd64
  - TEST_OS=freebsd TEST_ARCH=amd64
  - TEST_OS=openbsd TEST_ARCH=amd64
  - TEST_OS=openbsd TEST_ARCH=386
  - TEST_OS=openbsd TEST_ARCH=arm

matrix:
  allow_failures:
    - env: TEST_OS=openbsd TEST_ARCH=arm

install:

script:
  - GOARM=5 GO386=387 GOOS=$TEST_OS GOARCH=$TEST_ARCH go build -v
  - GOARM=5 GO386=387 GOOS=$TEST_OS GOARCH=$TEST_ARCH go test -c -v
  - if [[ $TEST_OS == "linux" && ($TEST_ARCH == "386" || $TEST_ARCH == "amd64") ]]; then GO386=387 GOOS=$TEST_OS GOARCH=$TEST_ARCH go test -v ./...; fi


notifications:
  email:
    recipients:
      - albenik@gmail.com
    on_success: change
    on_failure: always

